// Code generated by generate_ast. DO NOT EDIT.

package ast

import (
	"errors"
)

type Expr interface {
	Accept(visitor ExprVisitor) (result interface{}, err error)
}

type Binary struct {
	left     Expr
	operator *token.Token
	right    Expr
}

type Grouping struct {
	expression Expr
}

type Literal struct {
	value Object
}

type Unary struct {
	operator *token.Token
	right    Expr
}
